"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ['SECRET_KEY']
except KeyError:
    raise ImproperlyConfigured(
        'SECRET_KEY ortam değişkeni tanımlı değil. Lokalde .env dosyasına, '
        'deploy ortamında (örn. Vercel) environment variables ayarlarına ekleyin.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]
# Vercel her deployment'a kendi alan adını sistem değişkeni olarak verir; ALLOWED_HOSTS'a
# elle yazmadan çalışması ve önizleme adreslerinin 400 vermemesi için otomatik eklenir.
ALLOWED_HOSTS += [
    host for host in (
        os.environ.get(name)
        for name in ('VERCEL_URL', 'VERCEL_BRANCH_URL', 'VERCEL_PROJECT_PRODUCTION_URL')
    ) if host
]

# Production (DEBUG=False) güvenlik ayarları. Lokal geliştirme http üzerinden
# çalıştığı için DEBUG=True iken devre dışı.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    # Vercel TLS'i proxy'de sonlandırır; bu başlık olmadan SSL redirect sonsuz döngüye girer.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS geri alınması zor bir ayar; küçük başlayıp deploy'un sağlıklı
    # çalıştığı görülünce artırılmalı.
    SECURE_HSTS_SECONDS = 3600


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'interviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'config.middleware.CookieLocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL') or f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}"

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
}


# Cache
# Hız sınırlama (rate limiting) için kullanılıyor. Vercel'in serverless
# fonksiyonları süreçler arası bellek paylaşmadığı için LocMemCache yerine
# veritabanı tabanlı bir cache kullanılıyor (zaten bağlı olduğumuz DB).
# https://docs.djangoproject.com/en/6.1/topics/cache/#database-caching

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

# Arayüz dili (docs §2.2 iki dilli arayüz): kaynak metinler Türkçe yazılır, İngilizce
# çeviri locale/en/LC_MESSAGES/django.po'dadır. Dili yalnızca çerez belirler
# (config/middleware.py); mülakat dili (Interview.language) bundan bağımsızdır.
LANGUAGES = [
    ('tr', 'Türkçe'),
    ('en', 'English'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Vercel build'inde collectstatic çalışmadığı için WhiteNoise dosyaları doğrudan
# STATICFILES_DIRS ve uygulama static klasörlerinden servis eder.
WHITENOISE_USE_FINDERS = True


# Authentication
# https://docs.djangoproject.com/en/6.1/topics/auth/default/

LOGIN_URL = '/giris/'
LOGIN_REDIRECT_URL = '/panel/'
LOGOUT_REDIRECT_URL = '/'

# Varsayılan ModelBackend, is_active=False kullanıcıları authenticate() içinde
# sessizce reddeder ve LoginForm.confirm_login_allowed hiç çağrılmaz; bu yüzden
# e-posta doğrulanmamış hesaba "hesabını doğrula" gibi özel bir mesaj gösteremeyiz.
# AllowAllUsersModelBackend is_active kontrolünü authenticate()'te atlar, kontrolü
# forma (accounts/forms.py::LoginForm) bırakır.
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']


# Gemini API
# https://ai.google.dev/gemini-api/docs

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL') or 'gemini-3.8-flash'
# Ücretsiz katman kotası MODEL BAŞINA sayılır (günde 20 istek). Birincil modelin kotası
# dolunca sırayla bu yedek modellere geçilir; her birinin ayrı günlük payı vardır.
GEMINI_FALLBACK_MODELS = [
    model.strip()
    for model in (
        os.environ.get('GEMINI_FALLBACK_MODELS')
        or 'gemini-3.7-flash,gemini-3.6-flash,gemini-3.5-flash,gemini-3.1-flash-lite'
    ).split(',')
    if model.strip()
]


# reCAPTCHA v2 (kayıt formu, bot koruması)
# https://www.google.com/recaptcha/admin ile site+secret key alınır.
if DEBUG:
    # Google'ın herkese açık test anahtarları: her zaman geçer, gerçek koruma sağlamaz.
    RECAPTCHA_PUBLIC_KEY = os.environ.get(
        'RECAPTCHA_PUBLIC_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
    )
    RECAPTCHA_PRIVATE_KEY = os.environ.get(
        'RECAPTCHA_PRIVATE_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
    )
else:
    try:
        RECAPTCHA_PUBLIC_KEY = os.environ['RECAPTCHA_PUBLIC_KEY']
        RECAPTCHA_PRIVATE_KEY = os.environ['RECAPTCHA_PRIVATE_KEY']
    except KeyError:
        raise ImproperlyConfigured(
            'RECAPTCHA_PUBLIC_KEY / RECAPTCHA_PRIVATE_KEY ortam değişkenleri tanımlı değil.'
        )


# Resend (kayıt e-posta doğrulaması). https://resend.com API anahtarı.
# Yerelde anahtar yoksa doğrulama bağlantısı gönderilmez, sunucu logunda görünür
# (bkz. accounts/emailing.py); üretimde anahtar zorunludur.
RESEND_FROM_EMAIL = os.environ.get(
    'RESEND_FROM_EMAIL', 'Mülakat Simülatörü <onboarding@resend.dev>'
)
if DEBUG:
    RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
else:
    try:
        RESEND_API_KEY = os.environ['RESEND_API_KEY']
    except KeyError:
        raise ImproperlyConfigured('RESEND_API_KEY ortam değişkeni tanımlı değil.')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Uygulama e-posta göndermiyor. Lokalde konsola yazılır; üretimde SMTP arka ucu
# seçilir (Django'nun `check --deploy`'u konsol ve dummy arka uçlarını hata sayar).
# SMTP yapılandırılmadığı için ileride kodda e-posta gönderilirse sessizce
# kaybolmaz, bağlantı hatası verir; o zaman gerçek bir SMTP servisi ayarlanmalıdır.
MAILERS = {
    'default': {
        'BACKEND': (
            'django.core.mail.backends.console.EmailBackend' if DEBUG
            else 'django.core.mail.backends.smtp.EmailBackend'
        ),
    },
}
