# Generated by Django 6.1.1 on 2026-09-18 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('junior_developer', 'Junior Yazılım Geliştirici'), ('frontend_developer', 'Frontend Geliştirici'), ('backend_developer', 'Backend Geliştirici'), ('data_analyst', 'Veri Analisti'), ('business_analyst', 'İş Analisti'), ('intern_general', 'Stajyer (Genel)')], max_length=30)),
                ('level', models.CharField(choices=[('intern', 'Stajyer'), ('junior', 'Junior')], max_length=10)),
                ('interview_type', models.CharField(choices=[('technical', 'Teknik'), ('behavioral', 'İK (Davranışsal)'), ('mixed', 'Karışık')], max_length=15)),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=2)),
                ('question_count', models.PositiveSmallIntegerField(choices=[(5, '5'), (8, '8'), (10, '10')])),
                ('status', models.CharField(choices=[('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı')], default='in_progress', max_length=15)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('summary', models.TextField(blank=True)),
                ('top_strength', models.TextField(blank=True)),
                ('top_improvement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('teknik', 'Teknik'), ('davranissal', 'Davranışsal')], max_length=15)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.PositiveSmallIntegerField()),
                ('strengths', models.TextField()),
                ('improvements', models.TextField()),
                ('sample_answer', models.TextField()),
                ('language_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.question')),
            ],
        ),
    ]
