# Generated by Django 6.1.1 on 2026-09-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Teknik'), ('behavioral', 'İK (Davranışsal)'), ('mixed', 'Karışık')], max_length=15, verbose_name='Mülakat Türü'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=2, verbose_name='Mülakat Dili'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='level',
            field=models.CharField(choices=[('intern', 'Stajyer'), ('junior', 'Junior')], max_length=10, verbose_name='Seviye'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='position',
            field=models.CharField(choices=[('junior_developer', 'Junior Yazılım Geliştirici'), ('frontend_developer', 'Frontend Geliştirici'), ('backend_developer', 'Backend Geliştirici'), ('data_analyst', 'Veri Analisti'), ('business_analyst', 'İş Analisti'), ('intern_general', 'Stajyer (Genel)')], max_length=30, verbose_name='Pozisyon'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question_count',
            field=models.PositiveSmallIntegerField(choices=[(5, '5'), (8, '8'), (10, '10')], verbose_name='Soru Sayısı'),
        ),
    ]
