# Generated by Django 6.1.1 on 2026-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interview_interview_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='job_posting',
            field=models.TextField(blank=True, db_default='', default='', verbose_name='İş ilanı'),
        ),
    ]
