# Generated by Django 6.1.1 on 2026-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_job_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='cv_based',
            field=models.BooleanField(db_default=False, default=False, verbose_name="CV'ye özel"),
        ),
    ]
