# Generated by Django 6.1.1 on 2026-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interview_cv_based'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'İngilizce')], max_length=2, verbose_name='Mülakat Dili'),
        ),
    ]
