# Generated by Django 6.1.1 on 2026-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_alter_interview_language_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='custom_position',
            field=models.CharField(blank=True, db_default='', default='', max_length=160, verbose_name='Özel pozisyon'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='position',
            field=models.CharField(choices=[('junior_developer', 'Junior Yazılım Geliştirici'), ('frontend_developer', 'Frontend Geliştirici'), ('backend_developer', 'Backend Geliştirici'), ('data_analyst', 'Veri Analisti'), ('business_analyst', 'İş Analisti'), ('intern_general', 'Stajyer (Genel)'), ('other', 'Diğer')], max_length=30, verbose_name='Pozisyon'),
        ),
    ]
